#!/bin/bash

set -e

if [ -n "$GH_TOKEN" ]; then
    # Only build the docs for commits on master.
    if (( "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" )); then
        git commit -am "Updated feedstocks. [ci skip]" | true
        git remote add pushable https://${GH_TOKEN}@github.com/conda-forge/conda-forge.github.io.git/ > /dev/null
        git push pushable new_site_content:master 2> /dev/null
    fi
fi
