#!/usr/bin/env bash

# This script is to be run in a TravisCI context.

set -e

if [ -n "$GH_TOKEN" ]; then
    # Make sure we are on the latest commit on `master` if we are planning to deploy the change.
    if (( "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" )); then
        git checkout master
    fi
fi
